"use strict";

import local from "next/font/local";
import "./globals.css";

// Define the font imports
const geistSans = local({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = local({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// Export metadata object
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// RootLayout component
function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}

export default RootLayout;
"use strict";

import local from "next/font/local";
import "./globals.css";

// Define the font imports
const geistSans = local({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = local({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// Export metadata object
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// RootLayout component
function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}

export default RootLayout;
